spacetelescope/stpipe

CHANGES.rst, scripts/strun, src/stpipe/exceptions.py
@jdavies-st pointed out that `NoDataOnDetectorError` is JWST-specific and probably not useful to keep in stpipe.  ~~This removes that exception from this package and adds more general handling of any `SystemExit` subclass.~~  This removes that exception and adds an `StpipeExitException` base class that jwst can use to cause the CLI to exit with a particular status code.
=> Create StpipeExitException for exiting CLI with a specific exit status

CHANGES.rst, src/stpipe/step.py
This change allows subclasses to define their own `output_ext`. The extension is used to define what output data format to use.
=> change default value of output_ext

CHANGES.rst, src/stpipe/step.py
Fixes [jwst #5789](https://github.com/spacetelescope/jwst/issues/5789)
Resolves [JP-1940](https://jira.stsci.edu/browse/JP-1940)
Not sure if this is the correct procedure, but a JP ticket filed with a jwst repo issue has been traced to an issue in stpipe - specifically, if a user provides both a config_file and specific step flags, the merging of the step flag dicts was not a deep merge but an overwrite. This is easily fixed by using a different, existing method that ensures nested dicts are appropriately merged.
=> JP-1940: Change method to combine kwargs with provided cfg args in .call()

CHANGES.rst, src/stpipe/config_parser.py, src/stpipe/step.py, tests/test_config_parser.py
Over in stdatamodels I'm working on making DataModel implement collections.abc.Mapping, but that causes ConfigObj to treat reference overrides as config sections instead of config values.  This PR updates the merge_config function so that only true dicts are treated as config sections.
=> Prevent ConfigObj from treating DataModel as a config section

CHANGES.rst, src/stpipe/pipeline.py
Addresses [JP-2520](https://jira.stsci.edu/browse/JP-2520)
Calwebb_spec2 was found to require >25 GB of memory during CRDS prefetch with an input dataset of size ~2 GB. 
This PR passes a datamodel containing only the primary header metadata but stripped of the data array to each step for CRDS reference fetching.
=> JP-2520: Pull out metadata to avoid passing full data array for crds reference gathering

CHANGES.rst, src/stpipe/pipeline.py
Resolves issue [JP-2498](https://jira.stsci.edu/browse/JP-2498)
For `Pipeline` classmethods, use the `log.delegator` logger for messaging.
=> JP-2498 For classmethods, use the delegator logger

CHANGES.rst, src/stpipe/pipeline.py
The modification made in #38 does not propagate metadata from ModelContainers, as the container itself contains no metadata with which to fetch references from CRDS. Taking from _precache_references() code below the code I added, I'm following in someone's footsteps by selecting ModelContainers on isinstance(input, Sequence). With this, I can grab the metadata from the single asn member (due to asn_n_members=1 in datamodel_open).
=> JP-2520: Bugfix for ModelContainers

CHANGES.rst, src/stpipe/step.py
This attempts to record a skipped step into the DataModel's cal_step dictionary using the step's alias as the dict key. Need to test against jwst before any thought of merging.
=> JP-2355: Attempt to record skip into cal_step using alias

CHANGES.rst, src/stpipe/cmdline.py, src/stpipe/pipeline.py, src/stpipe/step.py
Currently, running a pipeline while providing a pars-{step} file overwrites the user-supplied pars with the default pars. It appears as though a simple swap in a merge may be all that's required to get this functioning - the overwrite priority is now flipped for parameters which are specified in both the default spec and the user pars file.
Addresses [JP-2609](https://jira.stsci.edu/browse/JP-2609)
=> JP-2609: Fix ignored step-pars during cmdline pipeline run

CHANGES.rst, src/stpipe/step.py
This PR removes a log statement that dumps parameter values from parameter reference files retrieved from CRDS. In the event of a local pars-ref file supplied by the user, this log statement would show values that are later overridden and unused. Parameters used by each step are still logged at the start of each step's run().
=> JP-2608: Remove misleading log of CRDS pars-ref pars

CHANGES.rst, src/stpipe/pipeline.py, src/stpipe/step.py
The issue with the big memory increase was tracked down to how `ModelContainer.get_crds_parameters` was implemented. Every time it was called, it reopened the first model read in from the asn table, and called `get_crds_parameters` on it,  instead of calling `get_crds_parameters` directly on the already opened model. 
This means the fix should be in jwst.datamodels.container, however since the next jwst release is after the next romancal release I am implementing it here. I'll make the changes in jwst as well. After the next jwst release the code here can be simplified by just calling `model.get_crds_parameters` regardless of the model type.
Fixes AL-668
=> Update get_crds_reference to not use JWST specific calls

CHANGES.rst, src/stpipe/step.py
Recent changes to config creation and reference file gathering require a fix for ModelContainer input, so datamodel.crds_parameters() will be run on the contents of the ModelContainer and not the container itself.
=> Pull first model from ModelContainers before datamodel methods applied

.github/workflows/ci.yml, .readthedocs.yaml, docs/source/conf.py
I also created a readthedocs.org entry under my account, and gave @spacetelescope, @WilliamJamieson, and @nden maintainer access. The PR builds should start to run when `.readthedocs.yaml` is in the `master` branch.
=> add RTD configuration

CHANGES.rst, src/stpipe/cmdline.py, src/stpipe/pipeline.py, src/stpipe/step.py
Closes #69
Closes #71
Resolves [JP-3018](https://jira.stsci.edu/browse/JP-3018)
CC: @tapastro @hbushouse @stscieisenhamer @nden
This PR restores support for step's list arguments at the command line that was broken since #57 (or version `0.4.0`).
This PR essentially undoes most of the changes from #57 with exception of moving `_override_config_from_args()` in front of  `config = step_class.merge_config(config, config_file)` in `cmdline.just_the_step_from_cmdline()` - this was the only change compared to pre- #57 that was needed to fix the issue that #57 was addressing while not breaking support for list arguments.
-----
Here is my setup (use any MIRI imaging ASN as input data; non-MIRI might have different default values from CRDS):
For testing purposes, I created two step configuration …
=> JP-3018: Restore support for step list arguments at command line

CHANGES.rst, src/stpipe/step.py
When string arguments are passed in via the command line they are converted to FromCommandLine instances. Convert them back to strings before providing them as keyword arguments while building the step.
It appears this conversion is only needed to resolve the path of input and output files provided to the step
https://github.com/spacetelescope/stpipe/blob/454314bfd8cfd8764bfc55448bc7c1c2d0f6489f/src/stpipe/config_parser.py#L38-L46
This will hopefully fix the failing regression tests for https://github.com/spacetelescope/jwst/pull/7403 and other instances of similar failures.
=> convert FromCommandLine to str before building Step

.github/workflows/ci.yml
this package suffers from the same issue as gwcs: https://github.com/spacetelescope/gwcs/pull/444
jwst ignores the scripts directory for pytest
https://github.com/spacetelescope/jwst/blob/4285c4efb95bc368f36456e9e106e6aba6abd597/setup.cfg#L152
this PR replicates that ignore to address CI failures seen for:
#82
=> to match jwst testing, ignore scripts in jwst ci job

CHANGES.rst, pyproject.toml, src/stpipe/entry_points.py
~EDIT: The `astropy>=5.0.4` dependency has a `python >= 3.8` requirement:
https://github.com/astropy/astropy/blob/326435449ad8d859f1abf36800c3fb88d49c27ea/setup.cfg#L35
and the CI does not test 3.7. This PR increases the minimum python version to 3.8 which allows for use of importlib.metadata (see conversation below: https://github.com/spacetelescope/stpipe/pull/84#discussion_r1125726227)~
use of pkg_resources is discouraged:
https://setuptools.pypa.io/en/latest/pkg_resources.html
additionally, this should fix potential version conflicts where dependency versions are checked on entry point loading for pkg_resources which can cause tests in CI jobs to fail when testing against a development version. Here is one example:
jwst pins stdatamodels to <1.2
stdatamodels tests against jwst as part …
=> update entry_points to use importlib.metadata

CHANGES.rst, pyproject.toml
While testing the minimum ASDF version for #82 I noticed a few other minimum version issues.
The CI only tests python >= 3.8 (this PR updates the `pyproject.toml` minimum python version to reflect this).
I was unable to get the tests to pass locally (running in python 3.10) with the minimum versions lists in the `pyproject.toml`. The changes in this PR were sufficient to allow the tests to pass.
=> require python >= 3.8 and update minimum dependencies

.flake8, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, CHANGES.rst, pyproject.toml, tox.ini
This PR abstracts CI workflows to the OpenAstronomy workflows; this should reduce maintenance for updating and maintaining actions. Additionally, these changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.
- add `tox.ini` with `toxenv`s from Romancal
- test various Python versions on `ubuntu` and `macos`
- ~~use `ruff` instead of `flake8` to check lint rules~~ moved to #77
after merging, the Required Statuses should also be updated
=> refactor toxenvs, use OpenAstronomy workflows, and move MacOS jobs to schedule

docs/source/conf.py
`tomli` is implemented read-only as `tomllib` in Python 3.11; this change ensures that the documentation build doesn't fail in Python 3.11 and above
=> import `tomli` as `tomllib` for `docs` builds before Python 3.11

.github/CODEOWNERS, .pre-commit-config.yaml, CHANGES.rst, pyproject.toml, src/stpipe/datamodel.py, src/stpipe/extern/__init__.py, src/stpipe/extern/configobj/configobj.py, src/stpipe/extern/configobj/validate.py, src/stpipe/format_template.py, src/stpipe/log.py, src/stpipe/step.py
[`codespell`](https://github.com/codespell-project/codespell) is a tool which is designed to check for misspelled words in source code. This PR sets up a reasonable configuration for `codespell`, fixes all the errors `codespell` uncovered, and adds `codespell` to the basic style checks for `stpipe`. Note that `codespell` can both autofix many common misspellings and be configured to ignore some misspellings by adding words to the `ignore-words-list` in the `pyproject.toml` file.
Note that this PR is built on top of the changes in #80 and so should be merged after PR #80
=> Start using `codespell`

.readthedocs.yaml, docs/rtd_environment.yaml
Properly switches RTD to using `mamba` to build python environment.
=> Switch to using mamba for RTD

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, CHANGES.rst, pyproject.toml
Numpy is imminently dropping support for Python 3.8
=> drop support for Python 3.8

CHANGES.rst, pyproject.toml, src/stpipe/config_parser.py, src/stpipe/crds_client.py, src/stpipe/extern/configobj/validate.py
`romancal` has a dependency of `stdatamodels`; however, there should not be a dependency of the Roman pipeline on JWST pipeline specific packages.
The dependency is due to the `stdatamodels.s3_utils` module, which is a thing wrapper of the now unsupported `stsci-aws-utils` package. The introduction of `s3_utils` was largely due to an experiment to see if the `jwst` pipeline could load reference files from S3. While this experiment was apparently successful, it was intended to be a one-off demonstration and has been largely unused since it completed. @eslavich can provide more details. Moreover, the implantation of S3 support requires client code in `jwst` and `romancal` to know the source of input data (S3 or local filesystem) and handle the opening of internal files in a distinct …
=> Remove `stdatamodels` dependency

.pre-commit-config.yaml, CHANGES.rst, pyproject.toml, tests/test_logger.py
`flynt` is a tool to help update Python strings to using modern methods.
This PR applies `flynt` to `stpipe` and updates its `pre-commit` to continue to check that `flynt` does not find more things to upgrade.
=> Apply `flynt`

.github/workflows/changelog.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, tox.ini
tox 4.9 broke implicit calling of tox envs so that it only accepts explicitly referenced ones. This PR resolves this and does some CI maintenance
=> Fix issue with tox 4.9

CHANGES.rst, scripts/strun
This modifies the version printout from `strun` to include the version of any stpipe entry points, i.e. `jwst` and `romancal`.  I.e. it mimics what `stpipe --version` does.
```
$ strun --version
stpipe: 0.5.0
jwst: 1.11.3
```
Resolves https://github.com/spacetelescope/jwst/issues/7470
=> Print out jwst or romancal versions from strun --version

.readthedocs.yaml
RTD no longer supports any system_packages setting:
https://blog.readthedocs.com/drop-support-system-packages/
This PR removes the unused system_packages setting
=> remove unsupported system_packages rtd config setting

CHANGES.rst, src/stpipe/cmdline.py, src/stpipe/config_parser.py, src/stpipe/pipeline.py, src/stpipe/step.py, src/stpipe/utilities.py, tests/test_config_parser.py
Fixes #105 
The `preserve_comments` argument ends up mapping to the `_inspec` argument for `ConfigObj`. Setting this appears to break parsing of spec lines that contain inline comments with a closing parenthesis. The `preserve_comments` argument also appears to have no effect on parsing comments (aside from introducing the bug above).
This PR deprecates `preserve_comments` and removes internal usage of the `_inspec` argument. This should fix parsing inline comments for closing parenthesis (this is tested in the included test) and have no effect on comment parsing (also included in the test).
Doing a quick search through romancal and jwst I see no usage of the `preserve_comments` argument so I don't expect either of those packages to require updates. Hopefully regression tests (to be run …
=> deprecate `preserve_comments` fix spec parsing for inline comments with closing parenthesis

CHANGES.rst, src/stpipe/extern/configobj/validate.py
fixes #106 
This is a contrived example (which ultimately fails with `stpipe.config_parser.ValidationError: Config parameter 'foo': missing`):
```python
﻿﻿import stpipe
n = 65000
class Foo(stpipe.Step):
spec = "foo = " + ")" * n + "(" * n
f = Foo()
```
Running the above example with stpipe main takes ~12 seconds to fail. With this PR it takes ~0.7 seconds (on my machine).
As mentioned in #106 this seems like a low risk as the user could also write a step that includes a `while True`. It seems worthwhile to fix the regex as the replacement appears equivalent and faster.
=> replace regex in configobj

.github/workflows/ci.yml, .github/workflows/data.yml, tox.ini
closes #121 
to manually refresh the WebbPSF data cache, add the `update webbpsf data` label to a PR
=> retrieve WebbPSF data for downstream CI testing

tox.ini
`stpipe` has no direct `numpy` dependencies, any `numpy` related things within it are lingering effects of its extraction from JWST.
=> Remove lingering NumPy references 

.github/workflows/ci.yml, CHANGES.rst, src/stpipe/config.py
This fixes the following deprecation warning:
```
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC)
```
Note that when you pass any timezone to `datetime.now()`, it returns the offset from UTC (format +HH:MM) appended to the string.  The offset from UTC is always zero, and `datetime.utcnow()` didn't include it.  So here it is removed so that timestamps have a consistent format.
=> Fix datetime.utcnow() deprecation

.github/workflows/ci.yml, CONTRIBUTING.md, README.md
This PR updates the CI and docs to refer to a renamed "main" branch.
As no downstream package appears to reference a specific branch for stpipe (and instead uses the default branch) we should be able to:
- rename the default branch to "main"
- merge this PR
It's possible codecov may need to be updated to use "main" (if it's not using the default branch).
Github does quite a number of helpful things when the branch is renamed (see https://github.com/github/renaming#renaming-existing-branches) so if acceptable I would propose we rename the branch, merge this PR, and deal with any fallout (although I do not expect any).
xref: https://github.com/spacetelescope/stdatamodels/pull/247
=> prepare ci/docs for renaming default branch to main

CHANGES.rst, src/stpipe/step.py
This PR improves the consistency of the parameters used for `_datamodels_open` by providing `asn_n_members=1` for `Step` (to match what is done in `Pipeline`).
Fixes https://github.com/spacetelescope/jwst/issues/8262
Romancal regtests all pass: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/608/
JWST regtests show 4 unrelated errors: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1226/
(the same errors are seen in a run without this PR using the current JWST default branch: ttps://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1227/
=> Provide `asn_n_members=1` when opening dataset for `Step` to call `get_crds_parameters`

CHANGES.rst, src/stpipe/log.py, src/stpipe/step.py, tests/test_logger.py, tests/test_step.py
This fixes handling of `pathlib.Path` objects when used for input files for `Step`.
It also removes the old, deprecated `tmpdir` pytest fixture and replaces it with the modern `tmp_path` equivalent, which provides a `pathlib.Path` instance.
Resolves #139
=> Fix handling of pathlib.Path objects

.github/workflows/ci.yml, tox.ini
Fixes: https://github.com/spacetelescope/stpipe/issues/145
Add a `nolegacypath` tox factor that run pytest with `-p no:legacypath` which will produce errors if legacy "non-path" fixtures/features are used.
A tox factor was added to allow the downstream jobs (like romancal and jwst) to run without `-p no:legacypath` as we are mainly concerned here that stpipe does not use legacy path features in it's test suite (not the test suites of romancal and jwst).
=> enable nolegacypath tox factor

.github/workflows/ci.yml, CHANGES.rst, src/stpipe/config_parser.py, src/stpipe/format_template.py, src/stpipe/function_wrapper.py, src/stpipe/hooks.py, src/stpipe/step.py, src/stpipe/subproc.py, src/stpipe/utilities.py, tests/conftest.py, tests/test_abstract_datamodel.py, tests/test_hooks.py, tests/test_utilities.py, tox.ini
Currently pre- and post-hooks only work as strings pointing to importable Step subclasses.  This made sense back when the foreseen use case of the pipeline was with `strun` at the command line, where all args are strings.
This PR fixes hooks to work with our current use cases.  It adds the possibility of using a defined function or defined `Step` subclass as hook, or an instance with parameters set of a `Step` subclass.  And it tests all the cases.
So now a hook can be a list of a number of useful things, not just a list of strings.
Hooks before:
```python
post_hooks = ["mypackage.MyFirstStep", "mypackage.MySecondStep"]  # string pointing to Step subclass
post_hooks = ["mypackage.my_function"]  # string pointing to a function that is Step.process() equivalent
post_hooks = ["fitsinfo {0}"] …
```
=> Fix pre- and post-hooks

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, pyproject.toml, src/stpipe/step.py
resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)
propagate Astropy's deprecation of Python 3.9 to downstream packages
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:
=> [SCSB-145] require Python 3.10

.pre-commit-config.yaml, pyproject.toml, src/stpipe/cli/__init__.py, src/stpipe/cli/list.py, src/stpipe/cli/main.py, src/stpipe/cmdline.py, src/stpipe/config.py, src/stpipe/config_parser.py, src/stpipe/crds_client.py, src/stpipe/format_template.py, src/stpipe/function_wrapper.py, src/stpipe/hooks.py, src/stpipe/integration.py, src/stpipe/log.py, src/stpipe/pipeline.py, src/stpipe/step.py, src/stpipe/utilities.py, tests/test_format_template.py, tests/test_step.py
This repo includes many style checks etc that do not align with other spacetelescope repos. This PR updates the checks to align more closely with those in romancal and jwst by doing the following:
- disable the scientific python repo-review (this prevented other style check changes and has not been adopted as a standard for stsci)
- use black instead of ruff-format
- remove the many ruff rules enabled in the pyproject.toml (leaving the isort, pyupgrade, bandit, pyflakes and other rules to roughly align with jwst and romancal)
The main motivation for this is to keep a more consistent standard across the repositories. While working on the `ModelLibrary` it has been tested in jwst (aligned to match that style), then moved to romancal (which imposed a slightly different set of checks and …
=> align style checks with other spacetelescope repos

tox.ini
Numpy is not a direct dependency and the oldest versions of our dependencies don't pin numpy < 2.0 (and they don't work for numpy 2.0). To allow the oldest deps job to continue to be useful this PR adds a numpy < 2 pin for only the oldest deps job.
See https://github.com/spacetelescope/stpipe/actions/runs/9552146949/job/26328047481?pr=159 for the numerous failures from importing astropy.tables.
=> install numpy<2 in oldestdeps

CHANGES.rst, src/stpipe/pipeline.py, src/stpipe/step.py
This PR removes some unused code in stpipe. Most of this is related to filename generation which will hopefully be somewhat easier to understand after this PR:
- `Pipeline.set_input_filename`
- `Step.name_format`: ~Requires https://github.com/spacetelescope/jwst/pull/8539 to first remove the 1 usage in jwst.~
- `Step.resolve_file_name`
- the `format` argument to `Step.save_model`
- the `name_format` `component_format` and `separator` arguments to `Step._make_output_path`
- remove ([now unused](https://github.com/spacetelescope/jwst/pull/8542)) `Step.reference_uri_to_cache_path`
jwst regtests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1519/ shows 1 unrelated error (`test_duplicate_names` which randomly fails)
romancal regtests: …
=> Remove unused code to simplify filename generation

src/stpipe/cli/command.py
supersedes @AlexKurek's #166 with minor fix to decorator order
=> fix decorator deprecation

CHANGES.rst, docs/source/api.rst, docs/source/conf.py, docs/source/index.rst, docs/source/model_library.rst, src/stpipe/datamodel.py, src/stpipe/pipeline.py, src/stpipe/step.py
This PR adds additional user and developer documentation for `ModelLibrary`.
Several other docs are updated as this PR also set's a [default_role](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-default_role) of 'obj' for sphinx. This turns all default backtick annotated text into `py:obj` roles. This was done to make writing the `ModelLibrary` docs easier but also fixed quite a few links in the other docs. This does mean that literal text needs 2 backticks (as in seen in several of the non-library doc changes in this PR).
Link to generated docs: https://stpipe--168.org.readthedocs.build/en/168/
=> `AbstractModelLibrary` docs

CHANGES.rst, src/stpipe/library.py
This PR makes a minor change to `AbstractModelLibrary.map_function` to reduce memory usage. More details can be found in the issue but the tldr is that this prevents having 2x models in memory during `map_function`.
Fixes: https://github.com/spacetelescope/stpipe/issues/173
=> del model in map_function

.github/workflows/ci.yml, tox.ini
See https://github.com/spacetelescope/stcal/pull/297
These are the same changes adapted to this package.
Currently downstream testing of jwst and romancal end up using the pyproject.toml in this repository for determining pytest configuration.
This ends up with pytest using options in these downstream tests that differ from the options used by the downstream packages in their tests (when run in their own CI). This in turn results in lots of false failures in our downstream testing.
This PR changes how the jwst and romancal downstream tests to use the pytest options defined in the respective repositories.
- ``changes/<PR#>.doc.rst``: …
=> fix downstream ci

.github/workflows/ci.yml, changes/193.feature.rst
Update CI to test with python 3.13.
jwst downstream failure is unrelated see https://github.com/spacetelescope/stpipe/pull/191
</details>
=> support python 3.13

tests/conftest.py, tests/test_hooks.py
The current test_hooks file is skipped if jwst is not installed:
https://github.com/spacetelescope/stpipe/blob/0c3d37e9da963fac2f7e631a375df5f5d6e38ed5/tests/test_hooks.py#L3
This PR removes the `importorskip` and tests the hooks without requiring `jwst` is installed.
As this is a tests only change no regression tests were run and no changelog was added.
</details>
=> test hooks without requiring jwst

changes/201.bugfix.rst, docs/source/model_library.rst, src/stpipe/library.py
This PR adds a method `_model_to_exptype` to `AbstractModelLibrary` to allow jwst to control how `exptype` is determined when `ModelLibrary` is created from a list of models.
With https://github.com/spacetelescope/jwst/pull/8918 this will address JP-3787.
jwst regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/11487054306
Romancal regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/11487038188
show 1 unrelated failure matching main: https://github.com/spacetelescope/RegressionTests/actions/runs/11470564200/job/31920046203
Fixes https://github.com/spacetelescope/stpipe/issues/200
- …
=> add _model_to_exptype method to AbstractModelLibrary

changes/202.feature.rst, src/stpipe/cli/strun.py, src/stpipe/entry_points.py, src/stpipe/utilities.py, tests/test_utilities.py
If a user installs both romancal and jwst and runs the following:
```
strun resample some_file
```
strun will always find the resample step in jwst (even though romancal provides a resample step with the class alias "resample").
This PR adds the ability to filter steps found by strun by providing the package name as a "scope. With this PR a user could call:
```
strun romancal::resample some_file
```
to run resample from romancal or
```
strun jwst::resample some_file
```
to run resample from jwst.
Documentation in both packages will need to be updated minimally with a description that providing a package name may be required if multiple strun supported packages are provided.
- …
=> support selecting steps by package name for strun

changes/204.removal.rst, src/stpipe/step.py, tests/test_hooks.py
This PR deprecates `Step.__call__`.
https://github.com/spacetelescope/romancal/pull/1499 and https://github.com/spacetelescope/jwst/pull/8945 removed all uses of `Step.__call__` in romancal and jwst.
</details>
=> deprecate Step.__call__

changes/195.bugfix.rst, src/stpipe/step.py
Closes https://github.com/spacetelescope/roman_datamodels/issues/343
jwst regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/11804014366
romancal regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/11803229018
(it may be worthwhile to add a regression or unit test in romancal for the feature fixed in this PR in a follow-up romancal PR)
This PR standardizes how stpipe sets `meta.cal_step.<class_alias>` when a step is skipped. On main the behavior for a single roman datamodel (not a ModelLibrary) does not log the skip. Running the following on main:
```python
from romancal.pipeline import ExposurePipeline
elp = ExposurePipeline()
elp.saturation.skip = True
elp.refpix.skip = True
elp.linearity.skip = True
elp.dark_current.skip = …
```
=> standardize setattr use in skip

changes/214.bugfix.rst, src/stpipe/step.py, tests/test_hooks.py
Closes #203
Fixes pre-hooks by packing pre-hook results as tuples so they can be unpacked for subsequent hooks and step.
JWST regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/12659199288
Romancal regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/12659196940
</details>
=> fix pre_hooks

changes/217.bugfix.rst, src/stpipe/function_wrapper.py, src/stpipe/hooks.py, src/stpipe/subproc.py
This PR updates hooks to inherit `output_ext` from the hooked class.
Closes #216 
JWST regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/12938827091
Roman regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/12968661316
Regtests all passed
</details>
=> remove fits extension assumption for hooks

src/stpipe/cmdline.py
This PR removes 2 log messages containing:
- the computer hostname
- the computer os
As logs are recorded in roman files (and will likely soon be recorded in jwst files) we don't want this information in the logs.
</details>
=> remove hostname and os log messages

changes/229.feature.rst, src/stpipe/pipeline.py, src/stpipe/step.py, tests/test_library.py, tests/test_step.py
Closes #228
Partially resolves [JP-3949](https://jira.stsci.edu/browse/JP-3949)
This PR adds a class method `Step._get_crds_parameters` to allow subclasses to control how files/models are handled for determining crds parameters for fetching step configurations and reference files.
Combined with https://github.com/spacetelescope/stdatamodels/pull/445 this will allow jwst to more efficiently load models when only the metadata is needed (as is the case for crds).
Regtests all pass:
romancal regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/14038435767
jwst regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/14038446114
- …
=> add Step._get_crds_parameters

changes/234.bugfix.rst, changes/235.bug.rst, src/stpipe/step.py, tests/test_step.py
Resolves [AL-929](https://jira.stsci.edu/browse/AL-929)
This PR addresses an issue with custom reference files passed to the pipelines with `override_reftype`. Only the basename of the file is recorded in `datamodel.meta.ref_file.name` and the path to it is dropped. However, there are steps which need to use the exact reference files used by another step. They look for reference file names and location in `meta.ref_file`. Since the absolute path is lost the step crashes. The fix here is to preserve the full path if custom files are used.
Seven failures in jwst look unrelated and exists on other PRs.
https://github.com/spacetelescope/RegressionTests/actions/runs/15170686795
One expected failure in romancal, where the name of the file contains the full path. …
=> Use full path if overriding a reference file

changes/239.removal.rst, src/stpipe/step.py
Resolves [JP-3490](https://jira.stsci.edu/browse/JP-3490)
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn)
Remove the deprecated `__call__` method from stpipe steps.
</details>
=> Remove deprecated __call__ method

.pre-commit-config.yaml, src/stpipe/step.py, tests/test_step.py
uses a common `.pre-commit-config.yaml` with other repositories in pipeline dependencies
As of the creation of this PR, checks that would change any files are commented out.
</details>
=> consistent `pre-commit` config

changes/255.feature.rst, src/stpipe/cmdline.py, src/stpipe/log.py, src/stpipe/step.py, tests/test_hooks.py, tests/test_logger.py, tests/test_step.py
Partially resolves [JP-1866](https://jira.stsci.edu/browse/JP-1866)
Closes #245
Allow downstream packages to specify known loggers, to ensure all desired logging messages are captured without adding configuration to the root logger.
For jwst and romancal, the specific loggers desired can be specified by overriding the get_known_loggers method in JwstStep and RomanStep, respectively.
To allow downstream packages time to transition, the get_known_loggers method in the base class raises a DeprecationWarning and returns the root logger. This should behave identically to the current method, which always attaches configuration to the root logger. In the future, the base class should transition to returning only the "stpipe" logger; at that point, the DeprecationWarning can be removed.
No …
=> Allow downstream packages to specify known loggers
